name: REST API Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download and Setup Allure CLI
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
        tar -zxvf allure-2.24.0.tgz
        sudo mv allure-2.24.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Build with Maven and Run Tests
      run: mvn clean test

    - name: Generate Allure Report
      run: |
        allure generate target/allure-results --clean -o target/allure-report || true

    - name: Upload Allure Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: target/allure-report
